# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'article-form.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ArticleForm(object):
    def setupUi(self, ArticleForm):
        ArticleForm.setObjectName("ArticleForm")
        ArticleForm.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ArticleForm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(ArticleForm)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEditCode = QtWidgets.QLineEdit(ArticleForm)
        self.lineEditCode.setObjectName("lineEditCode")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditCode)
        self.label_3 = QtWidgets.QLabel(ArticleForm)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEditDesignation = QtWidgets.QLineEdit(ArticleForm)
        self.lineEditDesignation.setObjectName("lineEditDesignation")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditDesignation)
        self.label_2 = QtWidgets.QLabel(ArticleForm)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_4 = QtWidgets.QLabel(ArticleForm)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(ArticleForm)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(ArticleForm)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(ArticleForm)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.spinBoxQteStock = QtWidgets.QSpinBox(ArticleForm)
        self.spinBoxQteStock.setObjectName("spinBoxQteStock")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.spinBoxQteStock)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditBuyPrice = QtWidgets.QLineEdit(ArticleForm)
        self.lineEditBuyPrice.setObjectName("lineEditBuyPrice")
        self.horizontalLayout_2.addWidget(self.lineEditBuyPrice)
        self.label_8 = QtWidgets.QLabel(ArticleForm)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEditSellingPrice = QtWidgets.QLineEdit(ArticleForm)
        self.lineEditSellingPrice.setObjectName("lineEditSellingPrice")
        self.horizontalLayout_3.addWidget(self.lineEditSellingPrice)
        self.label_9 = QtWidgets.QLabel(ArticleForm)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.comboBoxFamilly = QtWidgets.QComboBox(ArticleForm)
        self.comboBoxFamilly.setEditable(True)
        self.comboBoxFamilly.setCurrentText("")
        self.comboBoxFamilly.setObjectName("comboBoxFamilly")
        self.comboBoxFamilly.addItem("")
        self.comboBoxFamilly.addItem("")
        self.comboBoxFamilly.addItem("")
        self.comboBoxFamilly.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBoxFamilly)
        self.comboBoxAuthor = QtWidgets.QComboBox(ArticleForm)
        self.comboBoxAuthor.setEditable(True)
        self.comboBoxAuthor.setCurrentText("")
        self.comboBoxAuthor.setObjectName("comboBoxAuthor")
        self.comboBoxAuthor.addItem("")
        self.comboBoxAuthor.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBoxAuthor)
        self.label_10 = QtWidgets.QLabel(ArticleForm)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.comboBoxEditor = QtWidgets.QComboBox(ArticleForm)
        self.comboBoxEditor.setEditable(True)
        self.comboBoxEditor.setObjectName("comboBoxEditor")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBoxEditor)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButtonSave = QtWidgets.QPushButton(ArticleForm)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout.addWidget(self.pushButtonSave)
        self.pushButtonSaveAndQuit = QtWidgets.QPushButton(ArticleForm)
        self.pushButtonSaveAndQuit.setObjectName("pushButtonSaveAndQuit")
        self.horizontalLayout.addWidget(self.pushButtonSaveAndQuit)
        self.pushButtonQuit = QtWidgets.QPushButton(ArticleForm)
        self.pushButtonQuit.setObjectName("pushButtonQuit")
        self.horizontalLayout.addWidget(self.pushButtonQuit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(ArticleForm)
        self.comboBoxFamilly.setCurrentIndex(-1)
        self.comboBoxAuthor.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(ArticleForm)

    def retranslateUi(self, ArticleForm):
        _translate = QtCore.QCoreApplication.translate
        ArticleForm.setWindowTitle(_translate("ArticleForm", "Form"))
        self.label.setText(_translate("ArticleForm", "Code :"))
        self.lineEditCode.setInputMask(_translate("ArticleForm", "AAA99AA"))
        self.lineEditCode.setPlaceholderText(_translate("ArticleForm", "AAA99AA"))
        self.label_3.setText(_translate("ArticleForm", "Designation :"))
        self.label_2.setText(_translate("ArticleForm", "Famille :"))
        self.label_4.setText(_translate("ArticleForm", "Auteur :"))
        self.label_5.setText(_translate("ArticleForm", "Prix d\'achat :"))
        self.label_6.setText(_translate("ArticleForm", "Prix de vente :"))
        self.label_7.setText(_translate("ArticleForm", "Quantité stock :"))
        self.label_8.setText(_translate("ArticleForm", "F CFA"))
        self.label_9.setText(_translate("ArticleForm", "F CFA"))
        self.comboBoxFamilly.setItemText(0, _translate("ArticleForm", "Cassete"))
        self.comboBoxFamilly.setItemText(1, _translate("ArticleForm", "Divers sujets bibliques"))
        self.comboBoxFamilly.setItemText(2, _translate("ArticleForm", "Affiches"))
        self.comboBoxFamilly.setItemText(3, _translate("ArticleForm", "Bible"))
        self.comboBoxAuthor.setItemText(0, _translate("ArticleForm", "Smith M."))
        self.comboBoxAuthor.setItemText(1, _translate("ArticleForm", "Gilbert "))
        self.label_10.setText(_translate("ArticleForm", "Editeur :"))
        self.pushButtonSave.setText(_translate("ArticleForm", "Enregistrer"))
        self.pushButtonSaveAndQuit.setText(_translate("ArticleForm", "Enregistrer et quitter"))
        self.pushButtonQuit.setText(_translate("ArticleForm", "Quitter"))

