# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/ui/selling-form.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SellingFormWidget(object):
    def setupUi(self, SellingFormWidget):
        SellingFormWidget.setObjectName("SellingFormWidget")
        SellingFormWidget.resize(690, 414)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SellingFormWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(SellingFormWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEditClient = QtWidgets.QLineEdit(SellingFormWidget)
        self.lineEditClient.setObjectName("lineEditClient")
        self.horizontalLayout.addWidget(self.lineEditClient)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(SellingFormWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.comboBoxSellingType = QtWidgets.QComboBox(SellingFormWidget)
        self.comboBoxSellingType.setObjectName("comboBoxSellingType")
        self.comboBoxSellingType.addItem("")
        self.comboBoxSellingType.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBoxSellingType)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(SellingFormWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.dateEditSellingDate = QtWidgets.QDateEdit(SellingFormWidget)
        self.dateEditSellingDate.setCalendarPopup(True)
        self.dateEditSellingDate.setDate(QtCore.QDate(2000, 1, 2))
        self.dateEditSellingDate.setObjectName("dateEditSellingDate")
        self.horizontalLayout_2.addWidget(self.dateEditSellingDate)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableView = QtWidgets.QTableView(SellingFormWidget)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(SellingFormWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.labelTotalSelling = QtWidgets.QLabel(SellingFormWidget)
        self.labelTotalSelling.setObjectName("labelTotalSelling")
        self.horizontalLayout_5.addWidget(self.labelTotalSelling)
        self.label_6 = QtWidgets.QLabel(SellingFormWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonAddArticle = QtWidgets.QPushButton(SellingFormWidget)
        self.pushButtonAddArticle.setObjectName("pushButtonAddArticle")
        self.horizontalLayout_3.addWidget(self.pushButtonAddArticle)
        self.pushButtonDeleteArticle = QtWidgets.QPushButton(SellingFormWidget)
        self.pushButtonDeleteArticle.setEnabled(False)
        self.pushButtonDeleteArticle.setObjectName("pushButtonDeleteArticle")
        self.horizontalLayout_3.addWidget(self.pushButtonDeleteArticle)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.pushButtonSelling = QtWidgets.QPushButton(SellingFormWidget)
        self.pushButtonSelling.setEnabled(False)
        self.pushButtonSelling.setObjectName("pushButtonSelling")
        self.horizontalLayout_3.addWidget(self.pushButtonSelling)
        self.pushButtonQuit = QtWidgets.QPushButton(SellingFormWidget)
        self.pushButtonQuit.setObjectName("pushButtonQuit")
        self.horizontalLayout_3.addWidget(self.pushButtonQuit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(SellingFormWidget)
        QtCore.QMetaObject.connectSlotsByName(SellingFormWidget)

    def retranslateUi(self, SellingFormWidget):
        _translate = QtCore.QCoreApplication.translate
        SellingFormWidget.setWindowTitle(_translate("SellingFormWidget", "Vente d\'article"))
        self.label_2.setText(_translate("SellingFormWidget", "Nom complet du client :"))
        self.label_3.setText(_translate("SellingFormWidget", "Type de vente :"))
        self.comboBoxSellingType.setItemText(0, _translate("SellingFormWidget", "Détaillant"))
        self.comboBoxSellingType.setItemText(1, _translate("SellingFormWidget", "Grossiste"))
        self.label.setText(_translate("SellingFormWidget", "Date de vente :"))
        self.label_5.setText(_translate("SellingFormWidget", "Total des ventes :"))
        self.labelTotalSelling.setText(_translate("SellingFormWidget", "0"))
        self.label_6.setText(_translate("SellingFormWidget", "F CFA"))
        self.pushButtonAddArticle.setText(_translate("SellingFormWidget", " Ajouter un article"))
        self.pushButtonDeleteArticle.setText(_translate("SellingFormWidget", "Supprimer"))
        self.pushButtonSelling.setText(_translate("SellingFormWidget", "Vendre"))
        self.pushButtonQuit.setText(_translate("SellingFormWidget", "Quitter"))

